Profile: default
Region: us-east-1
SpecificationURL:
  us-east-2: "https://dnwj8swjjbsbt.cloudfront.net"
  us-east-1: "https://d1uauaxba7bl26.cloudfront.net"
  us-west-1: "https://d68hl49wbnanq.cloudfront.net"
  us-west-2: "https://d201a2mn26r7lk.cloudfront.net"
  ap-south-1: "https://d2senuesg1djtx.cloudfront.net"
  ap-northeast-2: "https://d1ane3fvebulky.cloudfront.net"
  ap-southeast-1: "https://doigdx0kgq9el.cloudfront.net"
  ap-southeast-2: "https://d2stg8d246z9di.cloudfront.net"
  ap-northeast-1: "https://d33vqc0rt9ld30.cloudfront.net"
  ca-central-1: "https://d2s8ygphhesbe7.cloudfront.net"
  eu-central-1: "https://d1mta8qj7i28i2.cloudfront.net"
  eu-west-1: "https://d3teyb21fexa9r.cloudfront.net"
  eu-west-2: "https://d1742qcu2c1ncx.cloudfront.net"
  sa-east-1: "https://d3c9jyj3w509b0.cloudfront.net"